//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        public decimal ID_ADMIN { get; set; }
        public string USUARIO_ADMIN { get; set; }
        public string EMAIL_ADMIN { get; set; }
        public string CONTRASEÑA_ADMIN { get; set; }
    }
}
