//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_EXTERNO
    {
        public decimal ID_CLIENTE2 { get; set; }
        public string NOMBRE_CLIENTE2 { get; set; }
        public string DIRECCION_CLIENTE2 { get; set; }
        public string TELEFONO_CLIENTE2 { get; set; }
        public string EMAIL_CLIENTE2 { get; set; }
        public string CONTRASEÑA_CLIENTE2 { get; set; }
    }
}
