//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFeriaVirtual.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FeriaEntities : DbContext
    {
        public FeriaEntities()
            : base("name=FeriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public DbSet<CLIENTE_EXTERNO> CLIENTE_EXTERNO { get; set; }
        public DbSet<CLIENTE_INTERNO> CLIENTE_INTERNO { get; set; }
    
        public virtual int AGREGAADMIN(string uSERADMIN, string eMAILADMIN, string cONTRAADMIN)
        {
            var uSERADMINParameter = uSERADMIN != null ?
                new ObjectParameter("USERADMIN", uSERADMIN) :
                new ObjectParameter("USERADMIN", typeof(string));
    
            var eMAILADMINParameter = eMAILADMIN != null ?
                new ObjectParameter("EMAILADMIN", eMAILADMIN) :
                new ObjectParameter("EMAILADMIN", typeof(string));
    
            var cONTRAADMINParameter = cONTRAADMIN != null ?
                new ObjectParameter("CONTRAADMIN", cONTRAADMIN) :
                new ObjectParameter("CONTRAADMIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGAADMIN", uSERADMINParameter, eMAILADMINParameter, cONTRAADMINParameter);
        }
    
        public virtual int AGREGARCLIENTEEXT(string nOMCLIENTE2, string dIRECLIENTE2, string fONOCLIENTE2, string cORREOCLIENTE2, string cONTRACLIENTE2)
        {
            var nOMCLIENTE2Parameter = nOMCLIENTE2 != null ?
                new ObjectParameter("NOMCLIENTE2", nOMCLIENTE2) :
                new ObjectParameter("NOMCLIENTE2", typeof(string));
    
            var dIRECLIENTE2Parameter = dIRECLIENTE2 != null ?
                new ObjectParameter("DIRECLIENTE2", dIRECLIENTE2) :
                new ObjectParameter("DIRECLIENTE2", typeof(string));
    
            var fONOCLIENTE2Parameter = fONOCLIENTE2 != null ?
                new ObjectParameter("FONOCLIENTE2", fONOCLIENTE2) :
                new ObjectParameter("FONOCLIENTE2", typeof(string));
    
            var cORREOCLIENTE2Parameter = cORREOCLIENTE2 != null ?
                new ObjectParameter("CORREOCLIENTE2", cORREOCLIENTE2) :
                new ObjectParameter("CORREOCLIENTE2", typeof(string));
    
            var cONTRACLIENTE2Parameter = cONTRACLIENTE2 != null ?
                new ObjectParameter("CONTRACLIENTE2", cONTRACLIENTE2) :
                new ObjectParameter("CONTRACLIENTE2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGARCLIENTEEXT", nOMCLIENTE2Parameter, dIRECLIENTE2Parameter, fONOCLIENTE2Parameter, cORREOCLIENTE2Parameter, cONTRACLIENTE2Parameter);
        }
    
        public virtual int AGREGARCLIENTEINT(string nOMCLIENTE1, string dIRECLIENTE1, string fONOCLIENTE1, string cORREOCLIENTE1, string cONTRACLIENTE1)
        {
            var nOMCLIENTE1Parameter = nOMCLIENTE1 != null ?
                new ObjectParameter("NOMCLIENTE1", nOMCLIENTE1) :
                new ObjectParameter("NOMCLIENTE1", typeof(string));
    
            var dIRECLIENTE1Parameter = dIRECLIENTE1 != null ?
                new ObjectParameter("DIRECLIENTE1", dIRECLIENTE1) :
                new ObjectParameter("DIRECLIENTE1", typeof(string));
    
            var fONOCLIENTE1Parameter = fONOCLIENTE1 != null ?
                new ObjectParameter("FONOCLIENTE1", fONOCLIENTE1) :
                new ObjectParameter("FONOCLIENTE1", typeof(string));
    
            var cORREOCLIENTE1Parameter = cORREOCLIENTE1 != null ?
                new ObjectParameter("CORREOCLIENTE1", cORREOCLIENTE1) :
                new ObjectParameter("CORREOCLIENTE1", typeof(string));
    
            var cONTRACLIENTE1Parameter = cONTRACLIENTE1 != null ?
                new ObjectParameter("CONTRACLIENTE1", cONTRACLIENTE1) :
                new ObjectParameter("CONTRACLIENTE1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGARCLIENTEINT", nOMCLIENTE1Parameter, dIRECLIENTE1Parameter, fONOCLIENTE1Parameter, cORREOCLIENTE1Parameter, cONTRACLIENTE1Parameter);
        }
    }
}
