//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCION
    {
        public OPCION()
        {
            this.VENTA_EXT = new HashSet<VENTA_EXT>();
        }
    
        public decimal ID_OPCION { get; set; }
        public string NOMBRE_OPCION { get; set; }
    
        public virtual ICollection<VENTA_EXT> VENTA_EXT { get; set; }
    }
}
