//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOR
    {
        public decimal ID_P { get; set; }
        public string NOMBRE_P { get; set; }
        public string EDAD_P { get; set; }
        public string TELEFONO_P { get; set; }
        public string DIRECCION_P { get; set; }
        public string EMAIL_P { get; set; }
        public string CONTRASEÑA_P { get; set; }
    }
}
