//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public decimal ID_PRODUCTO { get; set; }
        public decimal ID_TIPO { get; set; }
        public decimal STOCK_PRODUCTO { get; set; }
        public decimal PRECIO_PRODUCTO { get; set; }
        public string IMAGEN_PRODUCTO { get; set; }
    
        public virtual TIPO TIPO { get; set; }
    }
}
