//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION
    {
        public REGION()
        {
            this.CLIENTE_INTERNO = new HashSet<CLIENTE_INTERNO>();
        }
    
        public decimal ID_REGION { get; set; }
        public string NOMBRE_REGION { get; set; }
    
        public virtual ICollection<CLIENTE_INTERNO> CLIENTE_INTERNO { get; set; }
    }
}
