//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public decimal ID_SOLICITUD { get; set; }
        public decimal ID_TIPO { get; set; }
        public decimal ID_CALIDAD { get; set; }
        public decimal CANTIDAD_SOLICITUD { get; set; }
    
        public virtual CALIDAD CALIDAD { get; set; }
        public virtual TIPO TIPO { get; set; }
    }
}
