//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA_EXT
    {
        public decimal ID_VENTAE { get; set; }
        public System.DateTime FECHA_VENTAE { get; set; }
        public decimal ID_CLIENTE2 { get; set; }
        public decimal PRECIO_VENTAE { get; set; }
        public decimal ID_PRODUCTO { get; set; }
        public decimal ID_SOLICITUD { get; set; }
        public decimal ID_OPCION { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual SOLICITUD SOLICITUD { get; set; }
        public virtual OPCION OPCION { get; set; }
        public virtual CLIENTE_EXTERNO CLIENTE_EXTERNO { get; set; }
    }
}
